# Generated by Django 5.1.6 on 2025-03-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('librarian', 'Librarian'), ('member', 'Member'), ('admin', 'Admin')], default='member', max_length=10),
        ),
    ]
